---

- hosts: controller_nodes
  become: true
  roles:
    - role: keystone
    - role: rabbitmq
    - role: glance
    - role: placement-api
    - role: novaserver
    - role: neutronserver
    - role: horizon



- hosts: compute_nodes
  become: true
  roles:
    - role: novacompute
    - role: patch_nova_compute
    - role: libvirt_riscv
    - role: qemu
    - role: neutroncompute
    - role: neutron_dhcp

