CREATE DATABASE IF NOT EXISTS nova_api;
CREATE DATABASE IF NOT EXISTS nova;
CREATE DATABASE IF NOT EXISTS nova_cell0;


GRANT ALL PRIVILEGES ON nova_api.* TO '{{ NOVA_DB_USER }}'@'localhost' IDENTIFIED BY '{{ NOVA_DB_PASSWORD }}';
GRANT ALL PRIVILEGES ON nova_api.* TO '{{ NOVA_DB_USER }}'@'%' IDENTIFIED BY '{{ NOVA_DB_PASSWORD }}';

GRANT ALL PRIVILEGES ON nova.* TO '{{ NOVA_DB_USER }}'@'localhost' IDENTIFIED BY '{{ NOVA_DB_PASSWORD }}';
GRANT ALL PRIVILEGES ON nova.* TO '{{ NOVA_DB_USER }}'@'%' IDENTIFIED BY '{{ NOVA_DB_PASSWORD }}';

GRANT ALL PRIVILEGES ON nova_cell0.* TO '{{ NOVA_DB_USER }}'@'localhost'  IDENTIFIED BY '{{ NOVA_DB_PASSWORD }}';
GRANT ALL PRIVILEGES ON nova_cell0.* TO '{{ NOVA_DB_USER }}'@'%' IDENTIFIED BY '{{ NOVA_DB_PASSWORD }}';

