
- name: Configure hostname
  hostname:
    name: "{{ ansible_host_name }}"

- name: Configure Hosts
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    owner: root
    mode: 0644

- name: Populating /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host_private if item in groups['controller'] else hostvars[item].ansible_host }} {{ hostvars[item].ansible_host_name }} {{ item }}"
    state: present
  loop: "{{ groups['all'] }}"
  tags: host_config
