- name: openstack - Checking if user role "{{ PLACEMENT_USER }}" exists
  environment: '{{ keystone_admin_env }}'
  command: "/usr/bin/openstack user show {{ PLACEMENT_USER }}"
  ignore_errors: True
  register: placementapi_cmd_run

- name: openstack - Creating user  "{{ PLACEMENT_USER }}"
  environment: '{{ keystone_admin_env }}'
  command: "openstack user create --domain {{ OS_PROJECT_DOMAIN }} {{ PLACEMENT_USER }} --password {{ PLACEMENT_PASSWORD }}"
  when: placementapi_cmd_run is failed



- name: openstack - Adding user "{{ PLACEMENT_USER}}" to admin role
  environment: '{{ keystone_admin_env }}'
  command: "openstack role add --project {{ OS_PROJECT_NAME }} --user {{ PLACEMENT_USER }} admin"


