all:
  children:
    controller_nodes:
      hosts:
        controller01:
          ansible_host: 192.168.10.18
          ansible_ssh_user: sipeed
          ansible_host_name: controller01
          external_ip: 192.168.10.18
          internal_ip: 10.0.0.1
          ansible_host_full_name: controller01.licheenostrum.local


    compute_nodes:
      hosts:
        ln01:
          ansible_host: 10.0.0.10
          ansible_ssh_user: sipeed
          ansible_host_name: ln01
          external_ip: 10.0.0.10
          ansible_host_full_name: ln01.licheenostrum.local
        ln02:
          ansible_host: 10.0.0.12
          ansible_ssh_user: sipeed
          ansible_host_name: ln02
          external_ip: 10.0.0.12
          ansible_host_full_name: ln02.licheenostrum.local
        ln03:
          ansible_host: 10.0.0.14
          ansible_ssh_user: sipeed
          ansible_host_name: ln03
          external_ip: 10.0.0.14
          ansible_host_full_name: ln03.licheenostrum.local
        ln04:
          ansible_host: 10.0.0.16
          ansible_ssh_user: sipeed
          ansible_host_name: ln04
          external_ip: 10.0.0.16
          ansible_host_full_name: ln04.licheenostrum.local
      vars:
        ansible_ssh_common_args: >-
          -o ProxyCommand="ssh -p 22 -W %h:%p -q sipeed@licheenostrum.int.bsc.es"


    storage_nodes:
      hosts:
        st01:
          ansible_host: 10.0.0.18
          ansible_ssh_user: sipeed
          ansible_host_name: st01
          ansible_host_full_name: st01.licheenostrum.local
      vars:
        ansible_ssh_common_args: >-
          -o ProxyCommand="ssh -p 22 -W %h:%p -q sipeed@licheenostrum.int.bsc.es"
