---
- hosts: controller
  gather_facts: no
  tasks:
    - set_fact:
        rem_user: "{{ ansible_user | default(lookup('env','USER')) }}"
        rem_host: "{{ ansible_host }}"
    - local_action: command ssh-copy-id {{ rem_user }}@{{ rem_host }}
    - setup:


#- hosts: controller
#  become: yes
#  vars:
#    - dhcp_file: dhcpd_licheenostrum2.conf
#  tasks:
#    - import_tasks: tasks/desipeefy_repos.yml
#    - import_tasks: tasks/ntp.yml
#    - import_tasks: tasks/ssh_connection.yml
#    - import_tasks: tasks/host_config.yml
#    - import_tasks: tasks/controller.yml


#- hosts: controller
#  tasks:
#    - import_tasks: tasks/spread_sshkeys.yml



- hosts: compute
  become: yes
  tasks:
    - import_tasks: tasks/desipeefy_repos.yml
    - import_tasks: tasks/ntp.yml
    - import_tasks: tasks/ssh_connection.yml
    - import_tasks: tasks/host_config.yml


