#
### INSTALL PACKAGES
#
- name: Glance - Installing Package(s)
  apt:
    pkg:
      - glance


#
## DB
#
- name: Configuring DB, rendering SQL template (1/3)
  template:
    src: mysql.sql
    dest: /tmp/_glance.sql

- name: Configuring DB, running SQL commands (2/3)
  become: true
  shell: mysql -u root < /tmp/_glance.sql
  
- name: Configuring DB, removing SQL template  (3/3)
  ansible.builtin.file:
    path: /tmp/_glance.sql
    state: absent



- name: Glance - Configuring DB connection
  template:
    src: glance-api.conf
    dest: /etc/glance/glance-api.conf
  notify:
  - restart glance


#
## IMPORT DOMAIN TASKS
#
- import_tasks: domain.yml


- name: adding user role
  environment: '{{ keystone_admin_env }}'
  become: true
  command: openstack role add --user {{ GLANCE_DB_USER }} --user-domain {{ OS_USER_DOMAIN }} --system all reader


- name: running glance-manage db_sync
  environment: '{{ keystone_admin_env }}'
  become: true
  command: glance-manage db_sync





#
## restart service
#
- name: Waiting for service restart
  become: true
  service:
    name: glance-api
    state: restarted






