#
### INSTALL PACKAGES
#
- name: Horizon - Installing Package(s)
  apt:
    pkg:
      - openstack-dashboard
      - openstack-dashboard-apache
##Already installed by keystone
#     - libapache2-mod-wsgi-py3 

#
## Configure dashboard (Horizon) local_settings.py 
#

## Changed by a template below (GUILLEM)

#- name: Horizon - Configuring local_settings.py
#  lineinfile:
#    dest: /etc/openstack-dashboard/local_settings.py
#    regexp: ALLOWED_HOSTS
#    line: ALLOWED_HOSTS = [ '*' ]

#- name: Horizon - Configuring local_settings.py
#  lineinfile:
#    dest: /etc/openstack-dashboard/local_settings.py
#    regexp: OPENSTACK_KEYSTONE_URL
#    line: OPENSTACK_KEYSTONE_URL = "http://%s:5000/v3" % OPENSTACK_HOST

- name: Horizon - Configuring local_settings.py from template
  template:
    src: local_settings.py
    dest: /etc/openstack-dashboard/local_settings.py
    owner: root
    group: root
    mode: '0644'


## Commented due to %NAME% error -> Apache2: bad user name %USER%
# name: Horizon - Configuring apache2
# template:
#   src: apache.horizon.conf
#   dest: /etc/apache2/sites-enabled/horizon.conf

- name: Enabling ssl module within the apache2 configuration
  become: true
  command: sudo a2enmod ssl

- name: Horizon  - Waiting for Apache service restart
  become: true
  service:
    name: apache2
    state: restarted
    enabled: yes

