
CREATE DATABASE IF NOT EXISTS placement;

GRANT ALL PRIVILEGES ON placement.* TO '{{ PLACEMENT_USER }}'@'localhost' IDENTIFIED BY '{{ PLACEMENT_PASSWORD }}';
GRANT ALL PRIVILEGES ON placement.* TO '{{ PLACEMENT_USER }}'@'%' IDENTIFIED BY '{{ PLACEMENT_PASSWORD }}';

